/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion;

import co.com.hyunseda.market.access.Factory;
import co.com.hyunseda.market.access.IProductRepository;
import co.com.hyunseda.market.entities.Category;
import co.com.hyunseda.market.entities.Product;
import co.com.hyunseda.market.service.CategoryService;
import co.com.hyunseda.market.service.ProductService;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author JUAN CARLOS MELO
 */
public class AgregarProductoGUI extends javax.swing.JFrame {

    private final ProductService Pservice;
    private final CategoryService Cservice;
    private List<Category> category;

    /**
     * Creates new form AgregarProducto
     */
    public AgregarProductoGUI(CategoryService categoryService, ProductService productService) {
        initComponents();
        Pservice = productService;
        Cservice = categoryService;
        //loadCategories();
        loadAllProducts();
        setLocationRelativeTo(null);
        setSize(1000, 500);
        lstCategoriasSeleccionada.setModel(new DefaultListModel());
    }

    private void loadAllProducts() {
        try {
            category = Cservice.findAllCategories();
            DefaultListModel listModel = new DefaultListModel();

            for (Category category : category) {
                listModel.addElement(category.getId_category()+ "-" + category.getName());
            }
            lstSeleccionarCategorias.setModel(listModel);
        } catch (Exception ex) {
            Logger.getLogger(AgregarProductoGUI.class.getName()).log(Level.SEVERE, "Error al cargar platos", ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlNorte = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pnlSur = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtStock = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtDescripcion = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstSeleccionarCategorias = new javax.swing.JList<>();
        jLabel9 = new javax.swing.JLabel();
        txtUrlImagen = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtKeyword = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtCaracteristicas = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstCategoriasSeleccionada = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlNorte.add(jLabel1);

        jLabel2.setFont(new java.awt.Font("Cambria", 3, 18)); // NOI18N
        jLabel2.setText("Añadir Nuevo Producto");
        pnlNorte.add(jLabel2);

        getContentPane().add(pnlNorte, java.awt.BorderLayout.PAGE_START);

        jButton1.setText("Agregar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        pnlSur.add(jButton1);

        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        pnlSur.add(jButton2);

        getContentPane().add(pnlSur, java.awt.BorderLayout.PAGE_END);

        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        jPanel3.setLayout(new java.awt.GridLayout(9, 0));

        jLabel3.setText("Id :");
        jLabel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.add(jLabel3);

        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });
        txtId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIdKeyTyped(evt);
            }
        });
        jPanel3.add(txtId);

        jLabel4.setText("Nombre :");
        jLabel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.add(jLabel4);
        jPanel3.add(txtNombre);

        jLabel5.setText("Stock :");
        jLabel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.add(jLabel5);

        txtStock.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtStockKeyTyped(evt);
            }
        });
        jPanel3.add(txtStock);

        jLabel6.setText("Precio :");
        jLabel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.add(jLabel6);

        txtPrecio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPrecioKeyTyped(evt);
            }
        });
        jPanel3.add(txtPrecio);

        jLabel7.setText("Descripcion :");
        jLabel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.add(jLabel7);

        txtDescripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescripcionActionPerformed(evt);
            }
        });
        jPanel3.add(txtDescripcion);

        jLabel8.setText("Categoria :");
        jLabel8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.add(jLabel8);

        lstSeleccionarCategorias.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        lstSeleccionarCategorias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstSeleccionarCategoriasMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(lstSeleccionarCategorias);

        jPanel3.add(jScrollPane2);

        jLabel9.setText("Url Imagen :");
        jLabel9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.add(jLabel9);
        jPanel3.add(txtUrlImagen);

        jLabel10.setText("keyWord :");
        jLabel10.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.add(jLabel10);
        jPanel3.add(txtKeyword);

        jLabel11.setText("Caracteristicas :");
        jLabel11.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.add(jLabel11);
        jPanel3.add(txtCaracteristicas);

        jPanel1.add(jPanel3);

        jPanel2.setLayout(new java.awt.GridLayout(1, 0));

        lstCategoriasSeleccionada.setBorder(javax.swing.BorderFactory.createTitledBorder("Categoria Seleccionada"));
        jScrollPane1.setViewportView(lstCategoriasSeleccionada);

        jPanel2.add(jScrollPane1);

        jPanel1.add(jPanel2);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescripcionActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void lstSeleccionarCategoriasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstSeleccionarCategoriasMouseClicked

        DefaultListModel model = (DefaultListModel) lstCategoriasSeleccionada.getModel();
        if(!verificarCategoriaDuplicada(lstSeleccionarCategorias.getSelectedValue(),model)){
            model.addElement(lstSeleccionarCategorias.getSelectedValue());
        }
        
    }//GEN-LAST:event_lstSeleccionarCategoriasMouseClicked

    public boolean verificarCategoriaDuplicada(String categoriaAgregar,DefaultListModel model){
        for (int i = 0; i < model.size(); i++) {
            if(((String)model.getElementAt(i)).equals(categoriaAgregar)){
                return true;
            }
        }
        return false;
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(verificarCamposVacios()){
            JOptionPane.showMessageDialog(null, "Hay campos vacios", "Mensaje", JOptionPane.ERROR_MESSAGE);
            return;
        }
        Product aux = obtenerProductoFormulario();
        if(Pservice.saveProduct(aux)){
            JOptionPane.showMessageDialog(null, "Registro exitoso :3", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
        }else{
            JOptionPane.showMessageDialog(null, "Error inesperado:(", "Mensaje", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtStockKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtStockKeyTyped
        limitarNumeros(evt);
    }//GEN-LAST:event_txtStockKeyTyped

    private void txtPrecioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrecioKeyTyped
        limitarNumeros(evt);
    }//GEN-LAST:event_txtPrecioKeyTyped

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdActionPerformed

    private void txtIdKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdKeyTyped
        limitarNumeros(evt);
    }//GEN-LAST:event_txtIdKeyTyped
    
    public void limitarNumeros(KeyEvent e) {
        char c = e.getKeyChar();
        if (!Character.isDigit(c)) {
            e.consume(); // Ignorar el carácter no válido
        }
    }
    private Product obtenerProductoFormulario(){
        Long Id = Long.valueOf(txtId.getText());
        String nombre = txtNombre.getText();
        int Stock = Integer.parseInt(txtStock.getText());
        String descripcion = txtDescripcion.getText();
        String UrlImange = txtUrlImagen.getText();
        ArrayList<Category> aux = obtenerCategoriasProducto();
        Double Precio = Double.valueOf(txtPrecio.getText());
        String keyWords = txtKeyword.getText();
        String characteristics = txtCaracteristicas.getText();
        
        return new Product(Id, nombre, descripcion, Precio, Stock, keyWords, characteristics, UrlImange, aux);
    }
    private boolean verificarCamposVacios(){
        if(txtNombre.getText().isBlank() || txtDescripcion.getText().isBlank() || txtUrlImagen.getText().isBlank()|| lstCategoriasSeleccionada.getModel().getSize() == 0 || txtPrecio.getText().isBlank()
                || txtId.getText().isBlank() || txtCaracteristicas.getText().isBlank() || txtKeyword.getText().isBlank()){
            return true;
        }
        return false;
    }
    private ArrayList<Category> obtenerCategoriasProducto() {
        DefaultListModel model = (DefaultListModel) lstCategoriasSeleccionada.getModel();
        ArrayList<Category> elementos = new ArrayList<Category>();
        for (int i = 0; i < model.size(); i++) {
            String[] partes = ((String)model.getElementAt(i)).split("-");
            Category aux = new Category(Long.parseLong(partes[0]),partes[1]);
            elementos.add(aux);
        }
        return elementos;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> lstCategoriasSeleccionada;
    private javax.swing.JList<String> lstSeleccionarCategorias;
    private javax.swing.JPanel pnlNorte;
    private javax.swing.JPanel pnlSur;
    private javax.swing.JTextField txtCaracteristicas;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtKeyword;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtStock;
    private javax.swing.JTextField txtUrlImagen;
    // End of variables declaration//GEN-END:variables
}
